# Mode initial
InitialMode=Hiragana
# État de saisie partagé
InputState="Follow Global Configuration"
# Liste de propositions verticale
Vertical=True
# Étendre l'utilisation (requiert une liste de proposition verticale) 
ExpandMode=Always
# Fixer le curseur de pré-édition embarqué au début de la pré-édition
PreeditCursorPositionAtBeginning=False
# Raccourci clavier pour étendre l'utilisation
ExpandKey=Control+H
