# ─────────────────────────────────────────
#   Sasquatch-Dotfile — hyprland.conf
# ─────────────────────────────────────────

# ─── Modules ───────────────────────────
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/blur.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/layout.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/misc.conf
source = ~/.config/hypr/conf.d/rules.conf
source = ~/.config/hypr/keybinds.conf

# ─── Autostart ─────────────────────────
# autostart.sh lance : apply-wallpaper.sh (restauration fond), mako, polkit, wl-paste (text + image)…
exec-once = ~/.config/hypr/scripts/autostart.sh
