# hypridle.conf — régénéré par le panneau Settings (Super+I)

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Diminue luminosité après 180s
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 30%
    on-resume = brightnessctl -r
}

# Lock après 300s
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Écran off après 420s
listener {
    timeout = 420
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend après 900s
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
