# ─────────────────────────────────────────
#   Sasquatch-Dotfile — hyprland.conf
# ─────────────────────────────────────────

# ─── Modules ───────────────────────────
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/blur.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/layout.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/misc.conf
source = ~/.config/hypr/conf.d/rules.conf
source = ~/.config/hypr/keybinds.conf

# ─── Autostart ─────────────────────────
exec-once = ~/.config/hypr/scripts/autostart.sh

exec-once = mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waypaper --restore
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
    }
}


env = GTK_THEME,Catppuccin-Mocha-Standard-Blue-Dark
env = GTK_APPLICATION_PREFER_DARK_THEME,1
