# blur.conf
decoration {
    blur {
        enabled = true
        size = 8
        passes = 3
        noise = 0.02
        contrast = 0.9
        brightness = 0.85
        vibrancy = 0.2
        vibrancy_darkness = 0.3
        new_optimizations = true
        xray = true         # true = blur derrière toutes les fenêtres
        ignore_opacity = true 
    }
}


decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
    }
}
