# decoration.conf
decoration {
    rounding = 12

    # Transparence
    active_opacity   = 0.92
    inactive_opacity = 0.82
    fullscreen_opacity = 1.0

    # Ombre — sous-bloc shadow depuis Hyprland 0.45
    shadow {
        enabled       = true
        range         = 20
        render_power  = 3
        color         = rgba(00000066)
        color_inactive = rgba(00000033)
    }

    # Dim
    dim_inactive = true
    dim_strength = 0.1
}
